name: Lint

on:
  push:
    branches-ignore:
      - 'update-flake/**'
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint expressions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes

      - name: Install lint tools
        run: nix profile install nixpkgs#just nixpkgs#fd nixpkgs#statix nixpkgs#deadnix github:Swarsel/pedantix#pedantix-wrapped

      - name: Lint
        run: just lint check
